#!/bin/bash -x
export curlimage=appropriate/curl
export jqimage=stedolan/jq

apt update

arch=`uname -m`
if [ "$arch" == "x86_64" ]; then
  arch="amd64"
fi

if [ `command -v curl` ]; then
  curl -fsSL https://get.docker.com -o install-docker.sh
elif [ `command -v wget` ]; then
  wget -qO- https://get.docker.com -o install-docker.sh
fi

if [ -f install-docker.sh ]; then
  sh install-docker.sh --version ${docker_version_server}
else
  echo "Docker installation script not found."
  exit 1
fi

systemctl enable docker.service
systemctl start docker.service

usermod -a -G docker ubuntu

snap install aws-cli --classic
snap install kubectl --classic
snap install helm --classic

apt install -y unzip postgresql-client postgresql-client-common

curl -o /tmp/aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/${arch}/aws-iam-authenticator
chmod +x /tmp/aws-iam-authenticator
cp /tmp/aws-iam-authenticator /usr/local/bin/

curl -o /tmp/terraform_1.3.3_linux_${arch}.zip https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_${arch}.zip

unzip -d /tmp /tmp/terraform_1.3.3_linux_${arch}.zip

chmod +x /tmp/terraform

cp /tmp/terraform /usr/local/bin

curl -o /tmp/tofu_1.7.7_linux_${arch}.zip https://github.com/opentofu/opentofu/releases/download/v1.7.7/tofu_1.7.7_linux_${arch}.zip

unzip -d /tmp /tmp/tofu_1.7.7_linux_${arch}.zip

chmod +x /tmp/tofu

curl -o /tmp/terragrunt_linux_${arch} https://github.com/gruntwork-io/terragrunt/releases/download/v0.76.3/terragrunt_linux_${arch}

chmod +x /tmp/terragrunt_linux_${arch}

cp /tmp/terragrunt_linux_${arch} /usr/local/bin/terragrunt

